title: RINRUS docs
description: Prototype RINRUS documentation wiki
theme: just-the-docs

url: https://dwappett.github.io/rinrus_docs/

aux_links:
  Get RINRUS: https://github.com/natedey/RINRUS/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

enable_copy_code_button: true
aux_links_new_tab: true
nav_enabled: true

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: purple
  hl_yellow:
    color: yellow
  hl_purple:
    color: purple
  hl_green:
    color: green
  hl_g1:
    color: grey-lt
  hl_g2:
    color: grey-dk
